### ISSUE TITLE
!remind random

### ISSUE THREAD

**Issue by thomasrussellmurphy** [raidancampbell/swiggityspeare#12]
Have swiggity choose a 'random' time to post the reminder message and return a fuzzy/range confirmation for an estimation of when the reminder will come through. Potential ranges would be [1-30, 31-90, 91-270, ...] minutes. Times should probably be skewed to the low end of the range and not exceed a vaguely reasonable bot-uptime limit.

**Comment by ajm188** [comment]
:+1: 
I don't think it should return a confirmation...let's keep everyone in the dark :smile:

**Comment by raidancampbell** [comment]
I agree with @ajm188 on this, but I think that there should be some command confirmation in the meantime.  I'd like to know that swiggity received and is executing the reminder, instead of shouting into the void and hoping something answers.

**Comment by raidancampbell** [comment]
closed by 3f196063091ab10ae5a37e70133c2e9f24520095
