### ISSUE TITLE
Allow user's nick to be included in rnn query

### ISSUE THREAD

**Issue by raidancampbell** [raidancampbell/swiggityspeare#8]
if the neural network was trained on irc data, each message came from a user's nick.

When querying the network, if the user's nick is included in the query, this could allow for more accurate results from the network.  i.e. What other users would respond to *this* user saying this thing.

This is not a feature that should exist for shakespearean or non-irc networks, however.  Adding a nick to a shakespearean query would decrease the accuracy of the result.

**Comment by ajm188** [comment]
:+1:

**Comment by raidancampbell** [comment]
I can't think of a semi-decent way to incorporate this: an extra CLI switch at execution time is too redundant and strong.  Rough statistical analysis of the network's output is too messy / stochastic.

I'll leave this on hold unless someone comes up with a more elegant solution

**Comment by raidancampbell** [comment]
closed by aaa1975a8b25d9443375df2df615b46dc12a96b0
